name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        go: [1.8, 1.9, '1.10']
        go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16]

#    env:
#      GO111MODULE: on

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
#    - name: "Setup dependencies"
#      if: ${{ matrix.go == '1.8' }}
#      run: go get ./... && cd $GOPATH/src/github.com/stretchr/testify/ && git checkout v1.2.2 && cd -
    - name: Build
      run: go test -v ./...
